openapi: "3.0.0"
info:
  title: Order API
  version: 1.0.0
paths:
  /orders:
    post:
      summary: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  minLength: 1
                quantity:
                  type: integer
                  minimum: 1
                paymentMethod:
                  type: string
                  enum: [credit_card, paypal, wechat]
              required:
                - productId
                - quantity
      responses:
        '201':
          description: Order created
        '400':
          description: Invalid input
          
  /orders/{orderId}:
    get:
      summary: Get order details
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
        '404':
          description: Order not found
